//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace SATeC.PolizasPeriodoV13 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/PolizasPeriodo")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/PolizasPeriodo", IsNullable=false)]
    public partial class Polizas {
        
        private PolizasPoliza[] polizaField;
        
        private string versionField;
        
        private string rFCField;
        
        private PolizasMes mesField;
        
        private int anioField;
        
        private string tipoSolicitudField;
        
        private string numOrdenField;
        
        private string numTramiteField;
        
        private string selloField;
        
        private string noCertificadoField;
        
        private string certificadoField;
        
        public Polizas() {
            this.versionField = "1.3";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Poliza")]
        public PolizasPoliza[] Poliza {
            get {
                return this.polizaField;
            }
            set {
                this.polizaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PolizasMes Mes {
            get {
                return this.mesField;
            }
            set {
                this.mesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Anio {
            get {
                return this.anioField;
            }
            set {
                this.anioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TipoSolicitud {
            get {
                return this.tipoSolicitudField;
            }
            set {
                this.tipoSolicitudField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumOrden {
            get {
                return this.numOrdenField;
            }
            set {
                this.numOrdenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumTramite {
            get {
                return this.numTramiteField;
            }
            set {
                this.numTramiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Sello {
            get {
                return this.selloField;
            }
            set {
                this.selloField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string noCertificado {
            get {
                return this.noCertificadoField;
            }
            set {
                this.noCertificadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Certificado {
            get {
                return this.certificadoField;
            }
            set {
                this.certificadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/PolizasPeriodo")]
    public partial class PolizasPoliza {
        
        private PolizasPolizaTransaccion[] transaccionField;
        
        private string numUnIdenPolField;
        
        private System.DateTime fechaField;
        
        private string conceptoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transaccion")]
        public PolizasPolizaTransaccion[] Transaccion {
            get {
                return this.transaccionField;
            }
            set {
                this.transaccionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumUnIdenPol {
            get {
                return this.numUnIdenPolField;
            }
            set {
                this.numUnIdenPolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/PolizasPeriodo")]
    public partial class PolizasPolizaTransaccion {
        
        private PolizasPolizaTransaccionCompNal[] compNalField;
        
        private PolizasPolizaTransaccionCompNalOtr[] compNalOtrField;
        
        private PolizasPolizaTransaccionCompExt[] compExtField;
        
        private PolizasPolizaTransaccionCheque[] chequeField;
        
        private PolizasPolizaTransaccionTransferencia[] transferenciaField;
        
        private PolizasPolizaTransaccionOtrMetodoPago[] otrMetodoPagoField;
        
        private string numCtaField;
        
        private string desCtaField;
        
        private string conceptoField;
        
        private decimal debeField;
        
        private decimal haberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompNal")]
        public PolizasPolizaTransaccionCompNal[] CompNal {
            get {
                return this.compNalField;
            }
            set {
                this.compNalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompNalOtr")]
        public PolizasPolizaTransaccionCompNalOtr[] CompNalOtr {
            get {
                return this.compNalOtrField;
            }
            set {
                this.compNalOtrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompExt")]
        public PolizasPolizaTransaccionCompExt[] CompExt {
            get {
                return this.compExtField;
            }
            set {
                this.compExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cheque")]
        public PolizasPolizaTransaccionCheque[] Cheque {
            get {
                return this.chequeField;
            }
            set {
                this.chequeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Transferencia")]
        public PolizasPolizaTransaccionTransferencia[] Transferencia {
            get {
                return this.transferenciaField;
            }
            set {
                this.transferenciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OtrMetodoPago")]
        public PolizasPolizaTransaccionOtrMetodoPago[] OtrMetodoPago {
            get {
                return this.otrMetodoPagoField;
            }
            set {
                this.otrMetodoPagoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumCta {
            get {
                return this.numCtaField;
            }
            set {
                this.numCtaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string DesCta {
            get {
                return this.desCtaField;
            }
            set {
                this.desCtaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Concepto {
            get {
                return this.conceptoField;
            }
            set {
                this.conceptoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Debe {
            get {
                return this.debeField;
            }
            set {
                this.debeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Haber {
            get {
                return this.haberField;
            }
            set {
                this.haberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/PolizasPeriodo")]
    public partial class PolizasPolizaTransaccionCompNal {
        
        private string uUID_CFDIField;
        
        private string rFCField;
        
        private decimal montoTotalField;
        
        private string monedaField;
        
        private bool monedaFieldSpecified;
        
        private decimal tipCambField;
        
        private bool tipCambFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UUID_CFDI {
            get {
                return this.uUID_CFDIField;
            }
            set {
                this.uUID_CFDIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MontoTotal {
            get {
                return this.montoTotalField;
            }
            set {
                this.montoTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MonedaSpecified {
            get {
                return this.monedaFieldSpecified;
            }
            set {
                this.monedaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TipCamb {
            get {
                return this.tipCambField;
            }
            set {
                this.tipCambField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipCambSpecified {
            get {
                return this.tipCambFieldSpecified;
            }
            set {
                this.tipCambFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/CatalogosParaEsqContE")]
    public enum c_Moneda {
        
        /// <remarks/>
        AED,
        
        /// <remarks/>
        AFN,
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        AMD,
        
        /// <remarks/>
        ANG,
        
        /// <remarks/>
        AOA,
        
        /// <remarks/>
        ARS,
        
        /// <remarks/>
        AUD,
        
        /// <remarks/>
        AWG,
        
        /// <remarks/>
        AZN,
        
        /// <remarks/>
        BAM,
        
        /// <remarks/>
        BBD,
        
        /// <remarks/>
        BDT,
        
        /// <remarks/>
        BGN,
        
        /// <remarks/>
        BHD,
        
        /// <remarks/>
        BIF,
        
        /// <remarks/>
        BMD,
        
        /// <remarks/>
        BND,
        
        /// <remarks/>
        BOB,
        
        /// <remarks/>
        BOV,
        
        /// <remarks/>
        BRL,
        
        /// <remarks/>
        BSD,
        
        /// <remarks/>
        BTN,
        
        /// <remarks/>
        BWP,
        
        /// <remarks/>
        BYR,
        
        /// <remarks/>
        BZD,
        
        /// <remarks/>
        CAD,
        
        /// <remarks/>
        CDF,
        
        /// <remarks/>
        CHE,
        
        /// <remarks/>
        CHF,
        
        /// <remarks/>
        CHW,
        
        /// <remarks/>
        CLF,
        
        /// <remarks/>
        CLP,
        
        /// <remarks/>
        CNY,
        
        /// <remarks/>
        COP,
        
        /// <remarks/>
        COU,
        
        /// <remarks/>
        CRC,
        
        /// <remarks/>
        CUC,
        
        /// <remarks/>
        CUP,
        
        /// <remarks/>
        CVE,
        
        /// <remarks/>
        CZK,
        
        /// <remarks/>
        DJF,
        
        /// <remarks/>
        DKK,
        
        /// <remarks/>
        DOP,
        
        /// <remarks/>
        DZD,
        
        /// <remarks/>
        EGP,
        
        /// <remarks/>
        ERN,
        
        /// <remarks/>
        ETB,
        
        /// <remarks/>
        EUR,
        
        /// <remarks/>
        FJD,
        
        /// <remarks/>
        FKP,
        
        /// <remarks/>
        GBP,
        
        /// <remarks/>
        GEL,
        
        /// <remarks/>
        GHS,
        
        /// <remarks/>
        GIP,
        
        /// <remarks/>
        GMD,
        
        /// <remarks/>
        GNF,
        
        /// <remarks/>
        GTQ,
        
        /// <remarks/>
        GYD,
        
        /// <remarks/>
        HKD,
        
        /// <remarks/>
        HNL,
        
        /// <remarks/>
        HRK,
        
        /// <remarks/>
        HTG,
        
        /// <remarks/>
        HUF,
        
        /// <remarks/>
        IDR,
        
        /// <remarks/>
        ILS,
        
        /// <remarks/>
        INR,
        
        /// <remarks/>
        IQD,
        
        /// <remarks/>
        IRR,
        
        /// <remarks/>
        ISK,
        
        /// <remarks/>
        JMD,
        
        /// <remarks/>
        JOD,
        
        /// <remarks/>
        JPY,
        
        /// <remarks/>
        KES,
        
        /// <remarks/>
        KGS,
        
        /// <remarks/>
        KHR,
        
        /// <remarks/>
        KMF,
        
        /// <remarks/>
        KPW,
        
        /// <remarks/>
        KRW,
        
        /// <remarks/>
        KWD,
        
        /// <remarks/>
        KYD,
        
        /// <remarks/>
        KZT,
        
        /// <remarks/>
        LAK,
        
        /// <remarks/>
        LBP,
        
        /// <remarks/>
        LKR,
        
        /// <remarks/>
        LRD,
        
        /// <remarks/>
        LSL,
        
        /// <remarks/>
        LYD,
        
        /// <remarks/>
        MAD,
        
        /// <remarks/>
        MDL,
        
        /// <remarks/>
        MGA,
        
        /// <remarks/>
        MKD,
        
        /// <remarks/>
        MMK,
        
        /// <remarks/>
        MNT,
        
        /// <remarks/>
        MOP,
        
        /// <remarks/>
        MRO,
        
        /// <remarks/>
        MUR,
        
        /// <remarks/>
        MVR,
        
        /// <remarks/>
        MWK,
        
        /// <remarks/>
        MXN,
        
        /// <remarks/>
        MXV,
        
        /// <remarks/>
        MYR,
        
        /// <remarks/>
        MZN,
        
        /// <remarks/>
        NAD,
        
        /// <remarks/>
        NGN,
        
        /// <remarks/>
        NIO,
        
        /// <remarks/>
        NOK,
        
        /// <remarks/>
        NPR,
        
        /// <remarks/>
        NZD,
        
        /// <remarks/>
        OMR,
        
        /// <remarks/>
        PAB,
        
        /// <remarks/>
        PEN,
        
        /// <remarks/>
        PGK,
        
        /// <remarks/>
        PHP,
        
        /// <remarks/>
        PKR,
        
        /// <remarks/>
        PLN,
        
        /// <remarks/>
        PYG,
        
        /// <remarks/>
        QAR,
        
        /// <remarks/>
        RON,
        
        /// <remarks/>
        RSD,
        
        /// <remarks/>
        RUB,
        
        /// <remarks/>
        RWF,
        
        /// <remarks/>
        SAR,
        
        /// <remarks/>
        SBD,
        
        /// <remarks/>
        SCR,
        
        /// <remarks/>
        SDG,
        
        /// <remarks/>
        SEK,
        
        /// <remarks/>
        SGD,
        
        /// <remarks/>
        SHP,
        
        /// <remarks/>
        SLL,
        
        /// <remarks/>
        SOS,
        
        /// <remarks/>
        SRD,
        
        /// <remarks/>
        SSP,
        
        /// <remarks/>
        STD,
        
        /// <remarks/>
        SVC,
        
        /// <remarks/>
        SYP,
        
        /// <remarks/>
        SZL,
        
        /// <remarks/>
        THB,
        
        /// <remarks/>
        TJS,
        
        /// <remarks/>
        TMT,
        
        /// <remarks/>
        TND,
        
        /// <remarks/>
        TOP,
        
        /// <remarks/>
        TRY,
        
        /// <remarks/>
        TTD,
        
        /// <remarks/>
        TWD,
        
        /// <remarks/>
        TZS,
        
        /// <remarks/>
        UAH,
        
        /// <remarks/>
        UGX,
        
        /// <remarks/>
        USD,
        
        /// <remarks/>
        USN,
        
        /// <remarks/>
        UYI,
        
        /// <remarks/>
        UYU,
        
        /// <remarks/>
        UZS,
        
        /// <remarks/>
        VEF,
        
        /// <remarks/>
        VND,
        
        /// <remarks/>
        VUV,
        
        /// <remarks/>
        WST,
        
        /// <remarks/>
        XAF,
        
        /// <remarks/>
        XAG,
        
        /// <remarks/>
        XAU,
        
        /// <remarks/>
        XBA,
        
        /// <remarks/>
        XBB,
        
        /// <remarks/>
        XBC,
        
        /// <remarks/>
        XBD,
        
        /// <remarks/>
        XCD,
        
        /// <remarks/>
        XDR,
        
        /// <remarks/>
        XOF,
        
        /// <remarks/>
        XPD,
        
        /// <remarks/>
        XPF,
        
        /// <remarks/>
        XPT,
        
        /// <remarks/>
        XSU,
        
        /// <remarks/>
        XTS,
        
        /// <remarks/>
        XUA,
        
        /// <remarks/>
        XXX,
        
        /// <remarks/>
        YER,
        
        /// <remarks/>
        ZAR,
        
        /// <remarks/>
        ZMW,
        
        /// <remarks/>
        ZWL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/PolizasPeriodo")]
    public partial class PolizasPolizaTransaccionCompNalOtr {
        
        private string cFD_CBB_SerieField;
        
        private string cFD_CBB_NumFolField;
        
        private string rFCField;
        
        private decimal montoTotalField;
        
        private string monedaField;
        
        private bool monedaFieldSpecified;
        
        private decimal tipCambField;
        
        private bool tipCambFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CFD_CBB_Serie {
            get {
                return this.cFD_CBB_SerieField;
            }
            set {
                this.cFD_CBB_SerieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
        public string CFD_CBB_NumFol {
            get {
                return this.cFD_CBB_NumFolField;
            }
            set {
                this.cFD_CBB_NumFolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MontoTotal {
            get {
                return this.montoTotalField;
            }
            set {
                this.montoTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MonedaSpecified {
            get {
                return this.monedaFieldSpecified;
            }
            set {
                this.monedaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TipCamb {
            get {
                return this.tipCambField;
            }
            set {
                this.tipCambField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipCambSpecified {
            get {
                return this.tipCambFieldSpecified;
            }
            set {
                this.tipCambFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/PolizasPeriodo")]
    public partial class PolizasPolizaTransaccionCompExt {
        
        private string numFactExtField;
        
        private string taxIDField;
        
        private decimal montoTotalField;
        
        private string monedaField;
        
        private bool monedaFieldSpecified;
        
        private decimal tipCambField;
        
        private bool tipCambFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumFactExt {
            get {
                return this.numFactExtField;
            }
            set {
                this.numFactExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TaxID {
            get {
                return this.taxIDField;
            }
            set {
                this.taxIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal MontoTotal {
            get {
                return this.montoTotalField;
            }
            set {
                this.montoTotalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MonedaSpecified {
            get {
                return this.monedaFieldSpecified;
            }
            set {
                this.monedaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TipCamb {
            get {
                return this.tipCambField;
            }
            set {
                this.tipCambField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipCambSpecified {
            get {
                return this.tipCambFieldSpecified;
            }
            set {
                this.tipCambFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/PolizasPeriodo")]
    public partial class PolizasPolizaTransaccionCheque {
        
        private string numField;
        
        private string banEmisNalField;
        
        private string banEmisExtField;
        
        private string ctaOriField;
        
        private System.DateTime fechaField;
        
        private string benefField;
        
        private string rFCField;
        
        private decimal montoField;
        
        private string monedaField;
        
        private bool monedaFieldSpecified;
        
        private decimal tipCambField;
        
        private bool tipCambFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Num {
            get {
                return this.numField;
            }
            set {
                this.numField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BanEmisNal {
            get {
                return this.banEmisNalField;
            }
            set {
                this.banEmisNalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BanEmisExt {
            get {
                return this.banEmisExtField;
            }
            set {
                this.banEmisExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CtaOri {
            get {
                return this.ctaOriField;
            }
            set {
                this.ctaOriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Benef {
            get {
                return this.benefField;
            }
            set {
                this.benefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MonedaSpecified {
            get {
                return this.monedaFieldSpecified;
            }
            set {
                this.monedaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TipCamb {
            get {
                return this.tipCambField;
            }
            set {
                this.tipCambField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipCambSpecified {
            get {
                return this.tipCambFieldSpecified;
            }
            set {
                this.tipCambFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/CatalogosParaEsqContE")]
    public enum c_Banco {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("002")]
        Item002,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("006")]
        Item006,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("009")]
        Item009,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("012")]
        Item012,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("014")]
        Item014,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("019")]
        Item019,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("021")]
        Item021,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("030")]
        Item030,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("032")]
        Item032,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("036")]
        Item036,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("037")]
        Item037,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("042")]
        Item042,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("044")]
        Item044,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("058")]
        Item058,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("059")]
        Item059,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("060")]
        Item060,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("062")]
        Item062,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("072")]
        Item072,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("102")]
        Item102,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("103")]
        Item103,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("106")]
        Item106,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("108")]
        Item108,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("110")]
        Item110,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("112")]
        Item112,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("113")]
        Item113,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("116")]
        Item116,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("124")]
        Item124,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("126")]
        Item126,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("127")]
        Item127,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("128")]
        Item128,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("129")]
        Item129,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("130")]
        Item130,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("131")]
        Item131,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("132")]
        Item132,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("133")]
        Item133,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("134")]
        Item134,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("135")]
        Item135,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("136")]
        Item136,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("137")]
        Item137,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("138")]
        Item138,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("139")]
        Item139,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("140")]
        Item140,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("141")]
        Item141,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("143")]
        Item143,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("145")]
        Item145,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("166")]
        Item166,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("168")]
        Item168,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("600")]
        Item600,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("601")]
        Item601,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("602")]
        Item602,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("605")]
        Item605,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("606")]
        Item606,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("607")]
        Item607,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("608")]
        Item608,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("610")]
        Item610,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("614")]
        Item614,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("615")]
        Item615,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("616")]
        Item616,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("617")]
        Item617,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("618")]
        Item618,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("619")]
        Item619,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("620")]
        Item620,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("621")]
        Item621,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("622")]
        Item622,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("623")]
        Item623,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("626")]
        Item626,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("627")]
        Item627,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("628")]
        Item628,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("629")]
        Item629,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("630")]
        Item630,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("631")]
        Item631,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("632")]
        Item632,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("633")]
        Item633,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("634")]
        Item634,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("636")]
        Item636,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("637")]
        Item637,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("638")]
        Item638,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("640")]
        Item640,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("642")]
        Item642,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("646")]
        Item646,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("647")]
        Item647,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("648")]
        Item648,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("649")]
        Item649,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("651")]
        Item651,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("652")]
        Item652,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("653")]
        Item653,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("655")]
        Item655,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("656")]
        Item656,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("659")]
        Item659,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("901")]
        Item901,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("902")]
        Item902,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("670")]
        Item670,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("999")]
        Item999,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/PolizasPeriodo")]
    public partial class PolizasPolizaTransaccionTransferencia {
        
        private string ctaOriField;
        
        private string bancoOriNalField;
        
        private string bancoOriExtField;
        
        private string ctaDestField;
        
        private string bancoDestNalField;
        
        private string bancoDestExtField;
        
        private System.DateTime fechaField;
        
        private string benefField;
        
        private string rFCField;
        
        private decimal montoField;
        
        private string monedaField;
        
        private bool monedaFieldSpecified;
        
        private decimal tipCambField;
        
        private bool tipCambFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CtaOri {
            get {
                return this.ctaOriField;
            }
            set {
                this.ctaOriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BancoOriNal {
            get {
                return this.bancoOriNalField;
            }
            set {
                this.bancoOriNalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BancoOriExt {
            get {
                return this.bancoOriExtField;
            }
            set {
                this.bancoOriExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CtaDest {
            get {
                return this.ctaDestField;
            }
            set {
                this.ctaDestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BancoDestNal {
            get {
                return this.bancoDestNalField;
            }
            set {
                this.bancoDestNalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BancoDestExt {
            get {
                return this.bancoDestExtField;
            }
            set {
                this.bancoDestExtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Benef {
            get {
                return this.benefField;
            }
            set {
                this.benefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MonedaSpecified {
            get {
                return this.monedaFieldSpecified;
            }
            set {
                this.monedaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TipCamb {
            get {
                return this.tipCambField;
            }
            set {
                this.tipCambField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipCambSpecified {
            get {
                return this.tipCambFieldSpecified;
            }
            set {
                this.tipCambFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/PolizasPeriodo")]
    public partial class PolizasPolizaTransaccionOtrMetodoPago {
        
        private string metPagoPolField;
        
        private System.DateTime fechaField;
        
        private string benefField;
        
        private string rFCField;
        
        private decimal montoField;
        
        private string monedaField;
        
        private bool monedaFieldSpecified;
        
        private decimal tipCambField;
        
        private bool tipCambFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MetPagoPol {
            get {
                return this.metPagoPolField;
            }
            set {
                this.metPagoPolField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Benef {
            get {
                return this.benefField;
            }
            set {
                this.benefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RFC {
            get {
                return this.rFCField;
            }
            set {
                this.rFCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal Monto {
            get {
                return this.montoField;
            }
            set {
                this.montoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Moneda {
            get {
                return this.monedaField;
            }
            set {
                this.monedaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MonedaSpecified {
            get {
                return this.monedaFieldSpecified;
            }
            set {
                this.monedaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public decimal TipCamb {
            get {
                return this.tipCambField;
            }
            set {
                this.tipCambField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TipCambSpecified {
            get {
                return this.tipCambFieldSpecified;
            }
            set {
                this.tipCambFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/CatalogosParaEsqContE")]
    public enum c_MetPagos {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("13")]
        Item13,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("14")]
        Item14,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("16")]
        Item16,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("17")]
        Item17,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("98")]
        Item98,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99")]
        Item99,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.sat.gob.mx/esquemas/ContabilidadE/1_3/PolizasPeriodo")]
    public enum PolizasMes {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("04")]
        Item04,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("05")]
        Item05,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("06")]
        Item06,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("07")]
        Item07,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("08")]
        Item08,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("09")]
        Item09,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("11")]
        Item11,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("12")]
        Item12,
    }
}
